name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  terraform:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Initialise Terraform (no backend)
        run: terraform init -backend=false

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Run tfsec (IaC security scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra


  docker:
    name: Docker Image Build (Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build backend Docker image
        run: docker build -t fyp-app:ci -f src/backend/Dockerfile src/backend
